
kind: pipeline
name: Build and Deploy Ranutification
type: kubernetes


steps:
- name: build 
  image: plugins/docker
  settings:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: maxsurm/ranutif
    tags: ${DRONE_COMMIT_SHA}

trigger:
  branch:
  - master