replicaCount: 1

image:
  repository: maxsurm/ranutif
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "44c8f17a261819c8e0f11b3165490342842b9fd0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  letsencrypt: true
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt" # personal issuer

    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: notif.ranus.xyz
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ranutif-tls
      hosts:
        - notif.ranus.xyz

resources:
  limits:
    cpu: 10m
    memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
