name: PR creation workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
  check_suite:
    types: [completed]


jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}